wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714091335.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 98
      3:
      - 23
      4: 3.10.9
      5: 0.16.6
      6: 4.40.0
      8:
      - 5
      13: linux-x86_64
